export const CART_REQUEST = "CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const CART_FAILURE = "GET_FAILURE";
export const DELETE_CART = "DELETE_CART";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
